Repository linode/terraform-provider-linode, pull requests merged in 2019-11, with the labels that each got.

#65 Unhandled err variable
  linode/resource_linode_image.go
Labels: size/XS

#66 Test proving #62
  linode/resource_linode_instance_test.go
Labels: size/M

#62 This reapplies fixes from #44 for stackscript data
  linode/linode_instance_helpers.go
Labels: size/XS

#69 Preparing for release
  CHANGELOG.md
  go.mod
  go.sum
Labels: size/XS

#70 Update docs to include object storage
  linode/resource_linode_object_storage_bucket_test.go
  website/docs/d/object_storage_cluster.html.md
  website/docs/r/object_storage_bucket.html.md
  website/docs/r/object_storage_key.html.md
  website/linode.erb
Labels: documentation, size/M
