Repository linode/terraform-provider-linode, pull requests merged in 2019-04, with the labels that each got.

#38 fix resource attribute docs typo
  website/docs/r/stackscript.html.md
Labels: documentation, size/XS

#39 add missing type param for linode_domain
  website/docs/r/domain.html.md
  website/docs/r/domain_record.html.md
Labels: documentation, size/XS

#40 add linode_rdns resource
  CHANGELOG.md
  examples/main.tf
  examples/outputs.tf
  linode/data_source_linode_networking_ip.go
  linode/data_source_linode_networking_ip_test.go
  linode/linode_sweeper_test.go
  linode/provider.go
  linode/resource_linode_rdns.go
  linode/resource_linode_rdns_test.go
  website/docs/d/networking_ip.html.md
  website/docs/index.html.markdown
  website/docs/r/instance.html.md
  website/docs/r/rdns.html.md
  website/linode.erb
Labels: documentation, new-resource, size/XL

#41 Accept "0" in Domain and Domain Record time-in-seconds related fields
  CHANGELOG.md
  linode/provider.go
  linode/resource_linode_domain.go
  linode/resource_linode_domain_record.go
Labels: size/XS

#43 Don't repeat the "type" parameter in the linode_domain example
  website/docs/r/domain.html.md
Labels: documentation, size/XS
