Repository linode/terraform-provider-linode, pull requests merged in 2020-05, with the labels that each got.

#143 add linode_lke_cluster resource
  .travis.yml
  go.mod
  go.sum
  linode/provider.go
  linode/resource_linode_lke_cluster.go
  linode/resource_linode_lke_cluster_test.go
  website/docs/r/lke_cluster.html.md
  website/linode.erb
Labels: documentation, size/XL

#144 add linode_lke_cluster changelog entry
  CHANGELOG.md
Labels: size/XS

#146 increase golangci-lint timeout to 2m
  .golangci.yml
Labels: size/XS

#147 dont use xfilter for lke sweeper
  linode/resource_linode_lke_cluster_test.go
Labels: size/XS

#148 bump terraform-provider-sdk
  go.mod
  go.sum
  vendor/github.com/hashicorp/terraform-plugin-sdk/acctest/doc.go
  vendor/github.com/hashicorp/terraform-plugin-sdk/helper/resource/testing.go
  vendor/github.com/hashicorp/terraform-plugin-sdk/helper/resource/testing_new.go
  vendor/github.com/hashicorp/terraform-plugin-sdk/helper/resource/testing_new_config.go
  vendor/github.com/hashicorp/terraform-plugin-sdk/helper/schema/field_reader.go
  vendor/github.com/hashicorp/terraform-plugin-sdk/helper/schema/resource.go
  vendor/github.com/hashicorp/terraform-plugin-sdk/helper/schema/schema.go
  vendor/github.com/hashicorp/terraform-plugin-sdk/meta/meta.go
  vendor/github.com/hashicorp/terraform-plugin-sdk/terraform/state.go
  vendor/github.com/hashicorp/terraform-plugin-test/helper.go
  vendor/github.com/hashicorp/terraform-plugin-test/util.go
  vendor/modules.txt
Labels: dependencies, size/L

#149 Add link to region list
  website/docs/d/region.html.md
Labels: documentation, size/XS

#150 remove all resources Exists funcs
  linode/resource_linode_domain.go
  linode/resource_linode_domain_record.go
  linode/resource_linode_image.go
  linode/resource_linode_instance.go
  linode/resource_linode_nodebalancer.go
  linode/resource_linode_nodebalancer_config.go
  linode/resource_linode_nodebalancer_node.go
  linode/resource_linode_object_storage_bucket.go
  linode/resource_linode_rdns.go
  linode/resource_linode_sshkey.go
  linode/resource_linode_stackscript.go
  linode/resource_linode_template.go
  linode/resource_linode_token.go
  linode/resource_linode_volume.go
Labels: size/XL

#151 create test against updating a boot disk's image
  go.mod
  go.sum
  linode/helpers_test.go
  linode/resource_linode_instance_test.go
Labels: size/M

#153 add linode_firewall resource
  go.mod
  go.sum
  linode/expand.go
  linode/provider.go
  linode/resource_linode_firewall.go
  linode/resource_linode_firewall_test.go
  website/docs/r/firewall.html.md
  website/linode.erb
Labels: documentation, size/XL

#155 add 1.11 changelog entry
  CHANGELOG.md
Labels: size/XS

#156 update linodego and don't rely on volume timestamps
  CHANGELOG.md
  go.mod
  go.sum
  linode/linode_instance_helpers.go
  vendor/github.com/linode/linodego/instance_disks.go
  vendor/github.com/linode/linodego/volumes.go
  vendor/modules.txt
Labels: dependencies, size/S

#157 add Early Access documentation
  EARLY_ACCESS.md
  website/docs/r/firewall.html.md
Labels: documentation, size/XS
