Repository linode/terraform-provider-linode, pull requests merged in 2020-04, with the labels that each got.

#128 fix downsize without disk test
  linode/resource_linode_instance.go
  linode/resource_linode_instance_test.go
Labels: size/XS

#129 run gofmt check in CI
  GNUmakefile
Labels: size/XS

#131 Allow A record creation without a name
  linode/resource_linode_domain_record.go
Labels: size/XS

#130 detail resizing behavior
  website/docs/r/instance.html.md
Labels: documentation, size/XS

#132 get fullDiskSwapUpsize test passing
  linode/resource_linode_instance_test.go
Labels: size/XS

#133 add test against upsizing without explicit disk config
  linode/resource_linode_instance_test.go
Labels: size/XS

#134 remove deadcode
  .golangci.yml
  linode/linode_instance_helpers.go
  linode/resource_linode_instance.go
Labels: size/M

#120 Version go tools with go modules
  .travis.yml
  GNUmakefile
  go.mod
  go.sum
  tools.go
Labels: size/XL

#135 bump terraform-plugin-sdk and linodego deps
  go.mod
  go.sum
Labels: size/XS

#136 dont require name for non-SRV domain records
  linode/resource_linode_domain_record.go
  linode/resource_linode_domain_record_test.go
  website/docs/r/domain_record.html.md
Labels: documentation, size/M

#139 fix linode_networking_ip docs typo
  website/docs/d/networking_ip.html.md
Labels: documentation, size/XS

#141 setup specific issue templates
  .github/ISSUE_TEMPLATE/bug.md
  .github/ISSUE_TEMPLATE/enhancement.md
  .hashibot.hcl
Labels: size/M
