Repository linode/terraform-provider-linode, pull requests merged in 2020-02, with the labels that each got.

#80 add nodebalancer backup mode
  linode/resource_linode_nodebalancer_node.go
Labels: size/XS

#81 linode_object_storage_key.secret_key should be classified as sensitive
  linode/resource_linode_object_storage_key.go
Labels: size/XS

#82 make obj secret key accessible
  linode/resource_linode_object_storage_key.go
  linode/resource_linode_object_storage_key_test.go
Labels: size/S

#83 make linode_token.token attribute sensitive
  linode/resource_linode_token.go
Labels: size/XS

#84 format terraform examples
  examples/main.tf
Labels: size/XS

#85 add linode_domain_record datasource
  CHANGELOG.md
  linode/data_source_linode_domain_record.go
  linode/data_source_linode_domain_record_test.go
  linode/provider.go
  website/docs/d/domain_record.html.md
  website/linode.erb
Labels: documentation, new-data-source, size/XL

#86 Add stackscripts datasource
  CHANGELOG.md
  linode/data_source_linode_stackscript.go
  linode/data_source_linode_stackscript_test.go
  linode/linode_stackscript_helpers.go
  linode/provider.go
  linode/resource_linode_stackscript.go
  website/docs/d/stackscript.html.md
  website/linode.erb
Labels: documentation, size/XL

#88 make linode_domain_record.name computed for non-SRV records
  CHANGELOG.md
  linode/resource_linode_domain_record.go
  linode/resource_linode_domain_record_test.go
  website/docs/r/domain_record.html.md
Labels: documentation, size/L

#90 Fix linode domain record tests
  linode/data_source_linode_domain_record_test.go
Labels: size/XS

#89 Update dependencies
  CHANGELOG.md
  go.mod
  go.sum
  linode/data_source_linode_volume.go
Labels: size/S

#91 fix changelog typo
  CHANGELOG.md
Labels: size/XS

#92 format time for linode_volume data source
  linode/data_source_linode_volume.go
  linode/data_source_linode_volume_test.go
Labels: size/XS

#94 don't test import for datasources
  linode/data_source_linode_volume_test.go
Labels: size/XS

#95 add docs example for configuring rdns for multiple ips
  website/docs/r/rdns.html.md
Labels: documentation, size/XS

#96 avoid catching d.Set runtime errors in favor of testing
  linode/data_source_linode_domain.go
  linode/data_source_linode_profile.go
  linode/data_source_linode_volume.go
  linode/resource_linode_domain.go
  linode/resource_linode_instance.go
  linode/resource_linode_nodebalancer.go
  linode/resource_linode_nodebalancer_config.go
  linode/resource_linode_stackscript.go
Labels: size/M

#97 reuse instance device disk schema
  linode/resource_linode_instance.go
Labels: size/L

#98 implement swap disk resizing via swap_size attribute
  CHANGELOG.md
  linode/linode_instance_helpers.go
  linode/resource_linode_instance.go
  linode/resource_linode_instance_test.go
Labels: size/XL

#99 reuse testacc pubkey
  linode/data_source_linode_sshkey_test.go
  linode/linode_test.go
  linode/resource_linode_instance_test.go
  linode/resource_linode_sshkey_test.go
Labels: size/L
