Repository linode/terraform-provider-linode, pull requests merged in 2022-05, with the labels that each got.

#609 new: Add support for IPv4 sharing
  linode/helper/config.go
  linode/instance/helpers.go
  linode/instance/resource.go
  linode/instance/resource_test.go
  linode/instance/schema_resource.go
  linode/instance/tmpl/template.go
  linode/instance/tmpl/templates/ipv4_sharing.gotf
  linode/instance/tmpl/templates/ipv4_sharing_allocation.gotf
  linode/instance/tmpl/templates/ipv4_sharing_bad_input.gotf
  linode/instance/tmpl/templates/ipv4_sharing_empty.gotf
  website/docs/r/instance.html.md
Labels: enhancement

#631 fix: Resolve segfault in ID matching logic for linode_object_storage_bucket
  linode/objbucket/resource.go
  linode/objbucket/resource_test.go
  linode/objbucket/tmpl/lifecycle_no_id.gotf
  linode/objbucket/tmpl/template.go
Labels: bugfix

#633 fix: Hotfix ID matching logic for linode_object_storage_bucket read
  linode/objbucket/resource.go
  linode/objbucket/resource_test.go
  linode/objbucket/tmpl/lifecycle_no_id.gotf
  linode/objbucket/tmpl/template.go
Labels: bugfix

#640 Honor boot_config_label upon new resource creation
  linode/instance/resource.go
Labels: bugfix

#638 fix: Add DiffSuppressFunc for firewall IPv6 fields
  examples/mysql_adminer/main.tf
  linode/backup/datasource_test.go
  linode/firewall/schema_resource.go
  linode/firewall/tmpl/inst.gotf
  linode/helper/normalize.go
  linode/helper/normalize_test.go
  linode/rdns/tmpl/changed.gotf
  linode/rdns/tmpl/deleted.gotf
  linode/vlan/tmpl/data_basic.gotf
  linode/vlan/tmpl/data_regex.gotf
Labels: bugfix

#635 ref: Remove beta notices from DBaaS docs
  website/docs/d/database_engines.html.md
  website/docs/d/database_mysql.html.md
  website/docs/d/database_mysql_backups.html.md
  website/docs/d/databases.html.md
  website/docs/r/database_access_controls.md
  website/docs/r/database_mysql.html.md
Labels: docs

#636 new: Add `linode_instance_shared_ips` resource
  linode/instance/schema_resource.go
  linode/instancesharedips/resource.go
  linode/instancesharedips/resource_test.go
  linode/instancesharedips/schema_resource.go
  linode/instancesharedips/tmpl/configs.gotf
  linode/instancesharedips/tmpl/template.go
  linode/ipv6range/resource.go
  linode/provider.go
  website/docs/r/instance_shared_ips.html.md
  website/linode.erb
Labels: new-resource

#642 fix: Backport bug fixes from `dev` branch
  examples/mysql_adminer/main.tf
  linode/backup/datasource_test.go
  linode/firewall/schema_resource.go
  linode/firewall/tmpl/inst.gotf
  linode/helper/normalize.go
  linode/helper/normalize_test.go
  linode/instance/resource.go
  linode/rdns/tmpl/changed.gotf
  linode/rdns/tmpl/deleted.gotf
  linode/vlan/tmpl/data_basic.gotf
  linode/vlan/tmpl/data_regex.gotf
Labels: bugfix

#643 new: Add test to measure API request volume
  GNUmakefile
  linode/acceptance/test_util.go
  linode/instance/resource_test.go
  linode/instance/tmpl/template.go
  linode/instance/tmpl/templates/many_linodes.gotf
  linode/provider.go
Labels: tests, linodego-change

#648 doc: Add ignore_changes to LKE autoscaler example
  website/docs/r/instance_ip.html.md
  website/docs/r/lke_cluster.html.md
Labels: docs
