Repository linode/terraform-provider-linode, pull requests merged in 2024-05, with the labels that each got.

#1401 new: Add `linode_placement_group` resource
  docs/resources/placement_group.md
  go.mod
  go.sum
  linode/framework_provider.go
  linode/placementgroup/framework_models.go
  linode/placementgroup/framework_models_unit_test.go
  linode/placementgroup/framework_resource.go
  linode/placementgroup/framework_schema_resource.go
  linode/placementgroup/resource_test.go
  linode/placementgroup/tmpl/basic.gotf
  linode/placementgroup/tmpl/template.go
Labels: new-feature

#1406 new: Add Placement Group fields to `linode_instance` resource
  docs/resources/instance.md
  go.mod
  go.sum
  linode/helper/sdkv2_cty.go
  linode/helper/sdkv2_cty_test.go
  linode/instance/flatten.go
  linode/instance/helpers.go
  linode/instance/resource.go
  linode/instance/resource_test.go
  linode/instance/schema_resource.go
  linode/instance/tmpl/template.go
  linode/instance/tmpl/templates/with_pg.gotf
Labels: new-feature

#1405 Refactor firewall data source model
  linode/firewall/framework_datasource.go
  linode/firewall/framework_models.go
  linode/firewall/framework_models_unit_test.go
  linode/nb/framework_models.go
Labels: improvement

#1409 new: Add `linode_placement_group` data source
  docs/data-sources/placement_group.md
  linode/framework_provider.go
  linode/placementgroup/datasource_test.go
  linode/placementgroup/framework_datasource.go
  linode/placementgroup/framework_datasource_schema.go
  linode/placementgroup/framework_models.go
  linode/placementgroup/framework_resource.go
  linode/placementgroup/tmpl/data_basic.gotf
  linode/placementgroup/tmpl/template.go
Labels: new-feature

#1417 Fix concurrent map write on `Schema.Blocks` in the fw base resource
  linode/helper/framework_resource_base.go
Labels: bugfix

#1416 new: Add `linode_placement_groups` data source
  docs/resources/placement_groups.md
  linode/framework_provider.go
  linode/placementgroup/framework_datasource.go
  linode/placementgroup/framework_datasource_schema.go
  linode/placementgroup/framework_models.go
  linode/placementgroup/framework_models_unit_test.go
  linode/placementgroups/datasource_test.go
  linode/placementgroups/framework_datasource.go
  linode/placementgroups/framework_models.go
  linode/placementgroups/framework_schema_datasource.go
  linode/placementgroups/tmpl/data_basic.gotf
  linode/placementgroups/tmpl/template.go
Labels: new-feature

#1421 Remove explicit log for GET requests
  linode/account/framework_datasource.go
  linode/accountavailability/framework_datasource.go
  linode/accountlogin/framework_datasource.go
  linode/accountsettings/framework_datasource.go
  linode/accountsettings/framework_resource.go
  linode/backup/framework_datasource.go
  linode/domain/framework_datasource.go
  linode/domain/resource.go
  linode/domainrecord/framework_datasource.go
  linode/domainrecord/resource.go
  linode/firewall/framework_datasource.go
  linode/firewall/resource.go
  linode/firewalldevice/framework_resource.go
  linode/image/framework_datasource.go
  linode/image/framework_resource.go
  linode/instancedisk/framework_resource.go
  linode/instancesharedips/framework_resource.go
  linode/ipv6range/framework_datasource.go
  linode/ipv6range/framework_resource.go
  linode/kernel/framework_datasource.go
  linode/lke/framework_datasource.go
  linode/lke/resource.go
  linode/lkenodepool/framework_resource.go
  linode/nb/framework_datasource.go
  linode/nb/framework_resource.go
  linode/nbconfig/framework_datasource.go
  linode/nbconfig/framework_resource.go
  linode/nbnode/framework_datasource.go
  linode/nbnode/resource.go
  linode/networkingip/framework_datasource.go
  linode/objkey/framework_resource.go
  linode/profile/framework_datasource.go
  linode/rdns/framework_resource.go
  linode/region/framework_datasource.go
  linode/sshkey/framework_resource.go
  linode/stackscript/framework_datasource.go
  linode/stackscript/framework_resource.go
  linode/token/framework_resource.go
  linode/user/framework_datasource.go
  linode/user/resource.go
  linode/volume/framework_resource.go
  linode/vpc/framework_datasource.go
  linode/vpc/framework_resource.go
  linode/vpcsubnet/framework_datasource.go
  linode/vpcsubnet/framework_resource.go
Labels: improvement

#1429 test: Update profile integration tests and add unit test coverage
  linode/profile/datasource_test.go
  linode/profile/framework_models_unit_test.go
  linode/vpc/resource_test.go
Labels: testing

#1440 doc: Move `linode_placement_groups` data source docs to data-sources directory
  docs/data-sources/placement_groups.md
Labels: documentation

#1428 new: Add information about Placement Group limits to the `linode_region` and `linode_regions` data sources
  docs/data-sources/region.md
  docs/data-sources/regions.md
  linode/region/datasource_test.go
  linode/region/framework_datasource.go
  linode/region/framework_datasource_schema.go
  linode/region/framework_models.go
  linode/region/framework_models_unit_test.go
  linode/regions/datasource_test.go
  linode/regions/framework_datasource_schema.go
  linode/regions/framework_models.go
  linode/regions/framework_models_unit_test.go
Labels: new-feature

#1432 new: Add `linode_placement_group_assignment` resource
  docs/resources/instance.md
  docs/resources/placement_group_assignment.md
  linode/framework_provider.go
  linode/instance/schema_resource.go
  linode/placementgroup/resource_test.go
  linode/placementgroupassignment/framework_models.go
  linode/placementgroupassignment/framework_resource.go
  linode/placementgroupassignment/framework_resource_schema.go
  linode/placementgroupassignment/resource_test.go
  linode/placementgroupassignment/tmpl/basic.gotf
  linode/placementgroupassignment/tmpl/template.go
  linode/placementgroups/datasource_test.go
Labels: new-feature

#1449 fix: Ignore 404 when reading LKE ACL
  docs/resources/lke_cluster.md
  linode/lke/framework_datasource.go
  linode/lke/resource.go
Labels: bugfix
