Repository linode/terraform-provider-linode, pull requests merged in 2024-07, with the labels that each got.

#1493 Support Region for Object Storage Bucket Resource
  docs/resources/object_storage_bucket.md
  go.mod
  go.sum
  linode/helper/objects.go
  linode/obj/helpers.go
  linode/objbucket/resource.go
  linode/objbucket/resource_test.go
  linode/objbucket/schema_resource.go
  linode/objbucket/tmpl/basic.gotf
  linode/objbucket/tmpl/cert.gotf
  linode/objbucket/tmpl/template.go
  linode/objbucket/tmpl/updates.gotf
Labels: new-feature

#1492 project: MultiCluster Object Storage
  docs/resources/object_storage_bucket.md
  docs/resources/object_storage_key.md
  docs/resources/object_storage_object.md
  linode/acceptance/util.go
  linode/helper/compare.go
  linode/helper/objects.go
  linode/obj/helpers.go
  linode/obj/resource.go
  linode/obj/resource_test.go
  linode/obj/schema_resource.go
  linode/obj/tmpl/basic.gotf
  linode/obj/tmpl/creds_configed.gotf
  linode/obj/tmpl/temp_keys.gotf
  linode/obj/tmpl/template.go
  linode/obj/tmpl/updates.gotf
  linode/objbucket/datasource_test.go
  linode/objbucket/framework_datasource.go
  linode/objbucket/framework_datasource_schema.go
  linode/objbucket/resource.go
  linode/objbucket/resource_test.go
  linode/objbucket/schema_resource.go
  linode/objbucket/tmpl/access.gotf
  linode/objbucket/tmpl/basic.gotf
  linode/objbucket/tmpl/cert.gotf
  linode/objbucket/tmpl/creds_configed.gotf
  linode/objbucket/tmpl/data_basic.gotf
  linode/objbucket/tmpl/force_delete.gotf
  linode/objbucket/tmpl/lifecycle.gotf
  linode/objbucket/tmpl/lifecycle_no_id.gotf
  linode/objbucket/tmpl/temp_keys.gotf
  linode/objbucket/tmpl/template.go
  linode/objbucket/tmpl/updates.gotf
  linode/objbucket/tmpl/versioning.gotf
  linode/objcluster/framework_datasource_schema.go
  linode/objkey/framework_config_validation.go
  linode/objkey/framework_model.go
  linode/objkey/framework_models_unit_test.go
  linode/objkey/framework_resource.go
  linode/objkey/framework_resource_schema.go
  linode/objkey/resource_test.go
  linode/objkey/tmpl/limited.gotf
  linode/objkey/tmpl/template.go
Labels: new-feature

#1525 Add doc for `linode_object_storage_bucket` data source
  docs/data-sources/object_storage_bucket.md
Labels: documentation

#1523 Add project label
  .github/labels.yml
  .github/release.yml
Labels: repo-ci-improvement

#1521 VM Placement Changes for Terraform
  docs/data-sources/placement_group.md
  docs/data-sources/placement_groups.md
  docs/resources/instance.md
  docs/resources/placement_group.md
  docs/resources/placement_group_assignment.md
  go.mod
  go.sum
  linode/instance/flatten.go
  linode/instance/resource_test.go
  linode/instance/schema_resource.go
  linode/instance/tmpl/templates/with_pg.gotf
  linode/placementgroup/datasource_test.go
  linode/placementgroup/framework_datasource_schema.go
  linode/placementgroup/framework_models.go
  linode/placementgroup/framework_models_unit_test.go
  linode/placementgroup/framework_resource.go
  linode/placementgroup/framework_schema_resource.go
  linode/placementgroup/resource_test.go
  linode/placementgroup/tmpl/basic.gotf
  linode/placementgroup/tmpl/template.go
  linode/placementgroupassignment/tmpl/basic.gotf
  linode/placementgroups/datasource_test.go
  linode/placementgroups/framework_schema_datasource.go
  linode/placementgroups/tmpl/data_basic.gotf
Labels: breaking-change, do-not-merge

#1504 project: Linode Disk Encryption
  docs/data-sources/instances.md
  docs/data-sources/lke_cluster.md
  docs/resources/instance.md
  docs/resources/instance_disk.md
  docs/resources/lke_cluster.md
  docs/resources/lke_node_pool.md
  linode/instance/datasource.go
  linode/instance/datasource_test.go
  linode/instance/flatten.go
  linode/instance/resource.go
  linode/instance/resource_test.go
  linode/instance/schema_datasource.go
  linode/instance/schema_resource.go
  linode/instance/tmpl/template.go
  linode/instance/tmpl/templates/disk_encryption.gotf
  linode/instancedisk/framework_model.go
  linode/instancedisk/framework_resource_schema.go
  linode/instancedisk/resource_test.go
  linode/lke/cluster.go
  linode/lke/datasource_test.go
  linode/lke/framework_datasource_schema.go
  linode/lke/framework_models.go
  linode/lke/resource_test.go
  linode/lke/schema_resource.go
  linode/lke/tmpl/basic.gotf
  linode/lkenodepool/framework_models.go
  linode/lkenodepool/framework_models_unit_test.go
  linode/lkenodepool/framework_resource_schema.go
  linode/lkenodepool/framework_resource_test.go
Labels: new-feature

#1527 Add workflow job to verify registry publication after release
  .github/workflows/release.yml
Labels: repo-ci-improvement

#1524 Resolved createTempKeys failure when bucket is deleted
  linode/helper/objects.go
  linode/obj/resource.go
Labels: bugfix

#1533 fix: Fix LDE-related test failures
  linode/instance/resource_test.go
  linode/lke/cluster.go
  linode/lke/datasource_test.go
Labels: testing
