Repository linode/terraform-provider-linode, pull requests merged in 2024-08, with the labels that each got.

#1529 Added missing placement_group field to linode_instances data source
  docs/data-sources/instances.md
  linode/instance/datasource_test.go
  linode/instance/flatten.go
  linode/instance/resource.go
  linode/instance/schema_datasource.go
  linode/instance/tmpl/template.go
  linode/instance/tmpl/templates/data_with_pg.gotf
Labels: improvement

#1545 Handle unknown values in `objkey`'s config validate function
  linode/objkey/framework_config_validation.go
  linode/objkey/framework_resource.go
Labels: bugfix

#1547 Fix Multiple Issues in Object Storage Bucket and Key Resources
  linode/objkey/frameowkr_resource_test.go
  linode/objkey/framework_config_validation.go
  linode/objkey/framework_model.go
  linode/objkey/framework_resource.go
  linode/objkey/framework_resource_schema.go
  linode/objkey/helpers.go
  linode/objkey/tmpl/limited.gotf
Labels: bugfix

#1551 Allow wait for replications and update replica_regions requirements
  docs/resources/image.md
  go.mod
  go.sum
  linode/image/framework_models.go
  linode/image/framework_resource.go
  linode/image/framework_schema_resource.go
  linode/image/resource_test.go
  linode/image/tmpl/replicate.gotf
Labels: improvement

#1552 Fix test build
  linode/instance/datasource_test.go
Labels: ignore-for-release

#1554 ref: Temporarily revert Linode Disk Encryption project merge
  docs/data-sources/instances.md
  docs/data-sources/lke_cluster.md
  docs/resources/instance.md
  docs/resources/instance_disk.md
  docs/resources/lke_cluster.md
  docs/resources/lke_node_pool.md
  linode/instance/datasource.go
  linode/instance/datasource_test.go
  linode/instance/flatten.go
  linode/instance/resource.go
  linode/instance/resource_test.go
  linode/instance/schema_datasource.go
  linode/instance/schema_resource.go
  linode/instance/tmpl/template.go
  linode/instance/tmpl/templates/disk_encryption.gotf
  linode/instancedisk/framework_model.go
  linode/instancedisk/framework_resource_schema.go
  linode/instancedisk/resource_test.go
  linode/lke/cluster.go
  linode/lke/datasource_test.go
  linode/lke/framework_datasource_schema.go
  linode/lke/framework_models.go
  linode/lke/resource_test.go
  linode/lke/schema_resource.go
  linode/lke/tmpl/basic.gotf
  linode/lkenodepool/framework_models.go
  linode/lkenodepool/framework_models_unit_test.go
  linode/lkenodepool/framework_resource_schema.go
  linode/lkenodepool/framework_resource_test.go
Labels: ignore-for-release

#1555 test: Fix TestAccResourceInstance_privateImage integration test
  linode/instance/tmpl/templates/private_image.gotf
Labels: testing

#1550 Implemented VPC IP List data source
  docs/data-sources/vpc_ips.md
  linode/framework_provider.go
  linode/vpcips/datasource_test.go
  linode/vpcips/framework_datasource.go
  linode/vpcips/framework_models.go
  linode/vpcips/framework_schema_datasource.go
  linode/vpcips/tmpl/data_basic.gotf
  linode/vpcips/tmpl/template.go
Labels: new-feature

#1559 Add taints and labels support in LKE data source
  docs/data-sources/lke_cluster.md
  docs/resources/lke_node_pool.md
  linode/acceptance/util.go
  linode/acceptance/util_test.go
  linode/lke/framework_datasource_schema.go
  linode/lke/framework_datasource_test.go
  linode/lke/framework_models.go
  linode/lke/tmpl/autoscaler.gotf
  linode/lke/tmpl/data_taints_labels.gotf
  linode/lke/tmpl/template.go
  linode/lkenodepool/tmpl/nodepool.gotf
Labels: new-feature

#1568 Release v2.27.0
  docs/data-sources/lke_cluster.md
  docs/data-sources/vpc_ips.md
  docs/resources/lke_node_pool.md
  go.mod
  go.sum
  linode/acceptance/util.go
  linode/acceptance/util_test.go
  linode/framework_provider.go
  linode/helper/framework_data.go
  linode/helper/framework_schema.go
  linode/instancedisk/framework_resource.go
  linode/lke/framework_datasource_schema.go
  linode/lke/framework_datasource_test.go
  linode/lke/framework_models.go
  linode/lke/tmpl/autoscaler.gotf
  linode/lke/tmpl/data_taints_labels.gotf
  linode/lke/tmpl/template.go
  linode/lkenodepool/framework_models.go
  linode/lkenodepool/framework_models_unit_test.go
  linode/lkenodepool/framework_resource.go
  linode/lkenodepool/framework_resource_schema.go
  linode/lkenodepool/framework_resource_test.go
  linode/lkenodepool/tmpl/nodepool.gotf
  linode/lkenodepool/tmpl/template.go
  linode/vpcips/datasource_test.go
  linode/vpcips/framework_datasource.go
  linode/vpcips/framework_models.go
  linode/vpcips/framework_schema_datasource.go
  linode/vpcips/tmpl/data_basic.gotf
  linode/vpcips/tmpl/template.go
Labels: ignore-for-release
