Repository linode/terraform-provider-linode, pull requests merged in 2024-09, with the labels that each got.

#1563 Add validation for the accepted values of `device_name` attribute of instance config resource
  linode/instanceconfig/schema_resource.go
Labels: improvement

#1562 project: Linode Disk Encryption (re-merge)
  docs/data-sources/instances.md
  docs/data-sources/lke_cluster.md
  docs/resources/instance.md
  docs/resources/instance_disk.md
  docs/resources/lke_cluster.md
  docs/resources/lke_node_pool.md
  linode/instance/datasource.go
  linode/instance/datasource_test.go
  linode/instance/flatten.go
  linode/instance/resource.go
  linode/instance/resource_test.go
  linode/instance/schema_datasource.go
  linode/instance/schema_resource.go
  linode/instance/tmpl/template.go
  linode/instance/tmpl/templates/disk_encryption.gotf
  linode/instancedisk/framework_model.go
  linode/instancedisk/framework_resource_schema.go
  linode/instancedisk/resource_test.go
  linode/lke/cluster.go
  linode/lke/framework_datasource_schema.go
  linode/lke/framework_datasource_test.go
  linode/lke/framework_models.go
  linode/lke/resource_test.go
  linode/lke/schema_resource.go
  linode/lke/tmpl/basic.gotf
  linode/lkenodepool/framework_models.go
  linode/lkenodepool/framework_models_unit_test.go
  linode/lkenodepool/framework_resource_schema.go
  linode/lkenodepool/framework_resource_test.go
Labels: project

#1573 Fallback to cluster when region is not available in setting obj bucket resource ID
  linode/objbucket/resource.go
  linode/objbucket/resource_test.go
Labels: bugfix

#1426 Framework Migration: Firewall Resource
  go.mod
  go.sum
  linode/acceptance/tmpl/e2e_test_firewall.gotf
  linode/firewall/firewall_helpers_unit_test.go
  linode/firewall/framework_datasource_test.go
  linode/firewall/framework_models.go
  linode/firewall/framework_resource.go
  linode/firewall/framework_resource_test.go
  linode/firewall/framework_schema_datasource.go
  linode/firewall/framework_schema_resource.go
  linode/firewall/helpers.go
  linode/firewall/resource.go
  linode/firewall/schema_resource.go
  linode/firewall/tmpl/minimum.gotf
  linode/firewall/tmpl/no_ipv6.gotf
  linode/firewall/tmpl/template.go
  linode/framework_provider.go
  linode/helper/domain.go
  linode/helper/expand.go
  linode/helper/framework_conversion.go
  linode/helper/framework_data.go
  linode/nb/framework_models.go
  linode/nb/framework_resource_schema.go
  linode/nb/resource_test.go
  linode/nb/tmpl/firewall_updates.gotf
  linode/nb/tmpl/template.go
  linode/provider.go
  linode/token/framework_resource.go
Labels: improvement

#1574 Increase root pass length to 64 in tests
  linode/backup/datasource_test.go
  linode/instance/datasource_test.go
  linode/instance/resource_test.go
  linode/instanceconfig/resource_test.go
  linode/instancedisk/resource_test.go
  linode/nbnode/datasource_test.go
  linode/nbnode/resource_test.go
Labels: testing

#1582 Move the workaround of removing resource when empty ID up
  linode/firewall/framework_resource.go
Labels: bugfix

#1581 fix: Allow disks to be resized/deleted on instances that have been running for > 90 days
  linode/helper/instance.go
  linode/instance/helpers.go
  linode/instancedisk/framework_resource.go
  linode/instancedisk/helper.go
Labels: bugfix

#1566 test: Refactor smoke tests and add improve nightly workflow
  .github/workflows/integration_tests.yml
  .github/workflows/nightly_smoke_tests.yml
  Makefile
  linode/childaccount/datasource_test.go
  linode/databasepostgresql/resource_test.go
  linode/domain/datasource_test.go
  linode/domain/resource_test.go
  linode/firewall/framework_resource_test.go
  linode/firewalldevice/resource_test.go
  linode/instance/resource_test.go
  linode/instancedisk/resource_test.go
  linode/lke/framework_resource_test.go
  linode/nb/resource_test.go
  linode/objbucket/resource_test.go
  linode/regions/datasource_test.go
  linode/stackscript/resource_test.go
  linode/stackscripts/datasource_test.go
  linode/volume/resource_test.go
  linode/vpcsubnets/datasource_test.go
Labels: testing
