Repository linode/terraform-provider-linode, pull requests merged in 2024-03, with the labels that each got.

#1331 new: Populate route_target in linode_ipv6_range
  linode/ipv6range/framework_models.go
  linode/ipv6range/framework_resource.go
  linode/ipv6range/framework_schema_resource.go
  linode/ipv6range/resource_test.go
Labels: enhancement

#1333 doc: Add note to ssh key resource about ssh key generation
  docs/resources/sshkey.md
Labels: docs

#1344 fix: Check for errors before setting log fields in `linode_object_storage_key`
  linode/objkey/framework_resource.go
Labels: bug

#1360 new: Add `user_type` to user-related resources and data sources
  docs/data-sources/user.md
  docs/data-sources/users.md
  docs/resources/user.md
  go.mod
  go.sum
  linode/user/datasource_test.go
  linode/user/framework_datasource_schema.go
  linode/user/framework_models.go
  linode/user/resource.go
  linode/user/resource_test.go
  linode/user/schema_resource.go
  linode/users/datasource_test.go
  linode/users/framework_datasource_schema.go
Labels: enhancement

#1363 doc: Improve documentation around managing external LKE node pools; add migration guide metadata
  docs/guides/migrate_to_instance_config_and_disk_resources.md
  docs/resources/lke_cluster.md
  docs/resources/lke_node_pool.md
Labels: docs
