Repository linode/terraform-provider-linode, pull requests merged in 2024-10, with the labels that each got.

#1600 test: Fix slack payload in integration workflow
  .github/workflows/integration_tests.yml
Labels: testing

#1605 Fix Firewall Update
  linode/firewall/framework_models.go
  linode/firewall/framework_schema_resource.go
Labels: bugfix

#1591 Add support for LKE, Volume, NodeBalancer, and network transfer pricing endpoints
  linode/framework_provider.go
  linode/helper/base_pricing_types.go
  linode/instancetype/framework_datasource_schema.go
  linode/instancetype/framework_models.go
  linode/lketypes/datasource_test.go
  linode/lketypes/framework_datasource.go
  linode/lketypes/framework_datasource_schema.go
  linode/lketypes/framework_models.go
  linode/lketypes/tmpl/data_basic.gotf
  linode/lketypes/tmpl/template.go
  linode/nbtypes/datasource_test.go
  linode/nbtypes/framework_datasource.go
  linode/nbtypes/framework_datasource_schema.go
  linode/nbtypes/framework_models.go
  linode/nbtypes/tmpl/data_basic.gotf
  linode/nbtypes/tmpl/template.go
  linode/networktransferprices/datasource_test.go
  linode/networktransferprices/framework_datasource.go
  linode/networktransferprices/framework_datasource_schema.go
  linode/networktransferprices/framework_models.go
  linode/networktransferprices/tmpl/data_basic.gotf
  linode/networktransferprices/tmpl/template.go
  linode/volumetypes/datasource_test.go
  linode/volumetypes/framework_datasource.go
  linode/volumetypes/framework_datasource_schema.go
  linode/volumetypes/framework_models.go
  linode/volumetypes/tmpl/data_basic.gotf
  linode/volumetypes/tmpl/template.go
Labels: new-feature

#1614 Support configuring a provider-level Linode API CA file
  docs/index.md
  linode/framework_provider.go
  linode/framework_provider_config.go
  linode/helper/config.go
  linode/helper/filepath.go
  linode/helper/filepath_test.go
  linode/helper/framework_provider_model.go
  linode/helper/http.go
  linode/image/resource_test.go
  linode/provider.go
  linode/provider_test.go
Labels: new-feature

#1615 fix: Refresh placement group assignment in linode instance resource
  linode/instance/resource.go
Labels: bugfix

#1619 fix: Instance state has placement groups by default
  linode/instance/resource.go
Labels: bugfix

#1627 Support reconstructing absolute paths in ExpandPath(...)
  linode/helper/filepath.go
  linode/helper/filepath_test.go
Labels: bugfix

#1623 Added support for Block Storage Encryption
  docs/data-sources/instances.md
  docs/data-sources/volume.md
  docs/resources/volume.md
  go.mod
  go.sum
  linode/instance/datasource_test.go
  linode/instance/flatten.go
  linode/instance/resource.go
  linode/instance/schema_datasource.go
  linode/instance/schema_resource.go
  linode/instance/tmpl/template.go
  linode/instance/tmpl/templates/data_with_block_storage_encryption.gotf
  linode/volume/datasource_test.go
  linode/volume/framework_models.go
  linode/volume/framework_models_unit_test.go
  linode/volume/framework_resource.go
  linode/volume/framework_schema_datasource.go
  linode/volume/framework_schema_resource.go
  linode/volume/tmpl/data_with_block_storage_encryption.gotf
  linode/volume/tmpl/template.go
Labels: new-feature

#1624 fix: Instance disk nil pointer issue
  linode/instancedisk/framework_resource.go
Labels: bugfix

#1617 test: Add Cloud Firewall to LKE nodes after integration test execution
  .github/workflows/integration_tests.yml
  .github/workflows/integration_tests_pr.yml
Labels: repo-ci-improvement, testing

#1620 Remove Placement Group LA notices
  docs/data-sources/placement_group.md
  docs/data-sources/placement_groups.md
  docs/resources/instance.md
  docs/resources/placement_group.md
  docs/resources/placement_group_assignment.md
Labels: documentation

#1635 CI: Notify slack channel on releases
  .github/workflows/release-notify-slack.yml
Labels: repo-ci-improvement
