Repository linode/terraform-provider-linode, pull requests merged in 2024-04, with the labels that each got.

#1374 new: Allow importing linode_user; use ID in CRUD operations
  linode/user/resource.go
  linode/user/resource_test.go
Labels: enhancement

#1367 new: Add support for batch API requests
  linode/helper/batch.go
  linode/instance/resource.go
  linode/instanceconfig/resource.go
Labels: enhancement

#1371 new: Add `site_type` field to linode_region and linode_regions data sources
  docs/data-sources/region.md
  docs/data-sources/regions.md
  go.mod
  go.sum
  linode/region/datasource_test.go
  linode/region/framework_datasource_schema.go
  linode/region/framework_models.go
  linode/region/framework_models_unit_test.go
  linode/regions/datasource_test.go
  linode/regions/framework_datasource_schema.go
  linode/regions/framework_models.go
  linode/regions/framework_models_unit_test.go
Labels: enhancement

#1377 ref: Adjust log statements for consistency; remove redundant logs
  linode/accountlogin/framework_datasource.go
  linode/domain/framework_datasource.go
  linode/domain/resource.go
  linode/domainrecord/framework_datasource.go
  linode/domainrecord/resource.go
  linode/firewall/resource.go
  linode/firewalls/framework_datasource.go
  linode/helper/filter.go
  linode/helper/frameworkfilter/filter.go
  linode/helper/objects.go
  linode/image/framework_resource.go
  linode/instance/helpers.go
  linode/instance/resource.go
  linode/instanceconfig/resource.go
  linode/instancedisk/helper.go
  linode/instanceip/framework_resource.go
  linode/ipv6range/framework_resource.go
  linode/kernels/framework_datasource.go
  linode/nb/framework_resource.go
  linode/nbconfig/resource.go
  linode/obj/resource.go
  linode/objbucket/framework_datasource.go
  linode/objbucket/resource.go
  linode/objcluster/framework_datasource.go
  linode/objkey/framework_resource.go
  linode/regions/framework_datasource.go
  linode/sshkey/framework_resource.go
  linode/sshkeys/framework_datasource.go
  linode/token/framework_resource.go
  linode/vlan/framework_datasource.go
  linode/volume/framework_datasource.go
  linode/volume/framework_resource.go
Labels: refactor

#1378 doc: Bring provider documentation to parity with provider configuration options
  docs/index.md
  linode/provider.go
Labels: documentation

#1385 Add notice for externally managed node pools
  docs/resources/lke_node_pool.md
Labels: documentation

#1388 ci: add back keep and stale labels
  .github/labels.yml
Labels: repo-ci-improvement

#1390 Fix State Upgrader of NodeBalancer Resource
  linode/nb/framework_resource.go
Labels: bugfix

#1392 Utilize `BaseDataSource` in `linode_account` data source
  linode/account/framework_datasource.go
  linode/account/framework_datasource_schema.go
Labels: improvement

#1389 Migrate `linode_nodebalancer_config` resource to framework
  linode/framework_provider.go
  linode/helper/framework_conversion.go
  linode/instancenetworking/framework_models.go
  linode/nbconfig/framework_datasource.go
  linode/nbconfig/framework_models.go
  linode/nbconfig/framework_resource.go
  linode/nbconfig/framework_schema_resource.go
  linode/nbconfig/resource.go
  linode/nbconfig/resource_test.go
  linode/nbconfig/schema_resource.go
  linode/nbconfig/tmpl/basic.gotf
  linode/nbconfigs/tmpl/data_base.gotf
  linode/provider.go
Labels: improvement

#1396 Fix Sent to Closed Channel Panic in `helper.RunBatch`
  go.mod
  linode/helper/batch.go
  linode/instance/resource.go
  linode/instance/resource_test.go
  linode/instanceconfig/resource.go
Labels: bugfix

#1393 Fix rDNS condition in instanceip
  linode/instanceip/framework_resource.go
Labels: bugfix

#1391 new: Support `available` in accountavailability related data sources
  docs/data-sources/account_availabilities.md
  docs/data-sources/account_availability.md
  go.mod
  go.sum
  linode/accountavailabilities/datasource_test.go
  linode/accountavailabilities/framework_datasource_schema.go
  linode/accountavailabilities/framework_models_unit_test.go
  linode/accountavailability/datasource_test.go
  linode/accountavailability/framework_datasource_schema.go
  linode/accountavailability/framework_models.go
Labels: new-feature

#1399 Fix `kernels` integration test with updated filter
  linode/kernels/datasource_test.go
  linode/kernels/tmpl/data_filter.gotf
Labels: testing

#1398 Release v2.20.0
  .github/labels.yml
  docs/data-sources/account_availabilities.md
  docs/data-sources/account_availability.md
  go.mod
  go.sum
  linode/account/framework_datasource.go
  linode/account/framework_datasource_schema.go
  linode/accountavailabilities/datasource_test.go
  linode/accountavailabilities/framework_datasource_schema.go
  linode/accountavailabilities/framework_models_unit_test.go
  linode/accountavailability/datasource_test.go
  linode/accountavailability/framework_datasource_schema.go
  linode/accountavailability/framework_models.go
  linode/framework_provider.go
  linode/helper/batch.go
  linode/helper/framework_conversion.go
  linode/instance/resource.go
  linode/instance/resource_test.go
  linode/instanceconfig/resource.go
  linode/instanceip/framework_resource.go
  linode/instancenetworking/framework_models.go
  linode/kernels/datasource_test.go
  linode/kernels/tmpl/data_filter.gotf
  linode/nb/framework_resource.go
  linode/nbconfig/framework_datasource.go
  linode/nbconfig/framework_models.go
  linode/nbconfig/framework_resource.go
  linode/nbconfig/framework_schema_resource.go
  linode/nbconfig/resource.go
  linode/nbconfig/resource_test.go
  linode/nbconfig/schema_resource.go
  linode/nbconfig/tmpl/basic.gotf
  linode/nbconfigs/tmpl/data_base.gotf
  linode/provider.go
Labels: ignore-for-release

#1403 fix: Revert RunBatch(...) usage
  linode/helper/batch.go
  linode/instance/resource.go
  linode/instanceconfig/resource.go
Labels: bugfix
