Repository linode/terraform-provider-linode, pull requests merged in 2024-11, with the labels that each got.

#1595 Framework Migration: `linode_nodebalancer_node` Resource
  docs/resources/nodebalancer_node.md
  linode/framework_provider.go
  linode/nbnode/framework_models.go
  linode/nbnode/framework_resource.go
  linode/nbnode/framework_resource_schema.go
  linode/nbnode/resource.go
  linode/nbnode/schema_resource.go
  linode/provider.go
Labels: improvement

#1645 test: Skip LDE tests and remove LDE capability in testRegion
  linode/instance/resource_test.go
Labels: testing

#1638 Add documentation for pricing datasources
  docs/data-sources/lke_types.md
  docs/data-sources/network_transfer_prices.md
  docs/data-sources/nodebalancer_types.md
  docs/data-sources/volume_types.md
Labels: documentation

#1597 Terraform support for creation + assigning additional reserved IP to linode
  linode/framework_provider.go
  linode/instance/resource.go
  linode/instance/resource_test.go
  linode/instance/schema_resource.go
  linode/instance/tmpl/template.go
  linode/instance/tmpl/templates/instance_with_reserved_ip.gotf
  linode/instancereservedipassignment/framework_models.go
  linode/instancereservedipassignment/framework_resource.go
  linode/instancereservedipassignment/framework_schema.go
  linode/instancereservedipassignment/resource_test.go
  linode/instancereservedipassignment/tmpl/AddReservedIPToInstance.gotf
  linode/instancereservedipassignment/tmpl/template.go
Labels: new-feature

#1644 Fix Issue #1643 Update nodebalancer_config.md
  docs/resources/nodebalancer_config.md
Labels: documentation

#1650 docs - add ID to exported instance attributes
  docs/resources/instance.md
Labels: documentation

#1657 docs - add commit signing to contribution guidelines
  CONTRIBUTING.md
Labels: documentation

#1654 test: Enable disk encryption tests
  linode/instance/resource_test.go
Labels: testing

#1667 Release v2.31.1
  .github/workflows/integration_tests.yml
  .github/workflows/nightly_smoke_tests.yml
  .github/workflows/release-notify-slack.yml
  CONTRIBUTING.md
  docs/resources/instance.md
  go.mod
  go.sum
  linode/helper/regex.go
  linode/instance/resource_test.go
  linode/sshkey/framework_datasource_schema.go
  linode/sshkey/resource_test.go
Labels: ignore-for-release

#1672 fix: Broken documentation links
  docs/index.md
Labels: documentation

#1673 doc: Remove Image Services Gen2 LA notice #628
  docs/resources/image.md
Labels: documentation
