Repository linode/terraform-provider-linode, pull requests merged in 2024-06, with the labels that each got.

#1460 fix: Resolve issues that prevented goreleaser v2.x compatibility
  .goreleaser.yml
Labels: bugfix

#1461 Backport #1460 to dev
  .goreleaser.yml
Labels: bugfix

#1464 Add RequiresReplace plan modifier to linode_id for linode_instance_shared_ips resource
  linode/instancesharedips/framework_resource_schema.go
Labels: bugfix

#1470 doc: Add notes to documentation for limited LKE ACL availability
  docs/data-sources/lke_cluster.md
  docs/resources/lke_cluster.md
Labels: documentation

#1471 fix: Resolve nil pointer dereference in FrameworkProvider{}.InitProvider(...) method
  linode/framework_provider_config.go
Labels: bugfix

#1472 test: Add Calico Inbound and Outbound policies to LKE nodes for E2E
  .github/workflows/integration_tests.yml
  .github/workflows/integration_tests_pr.yml
  scripts/lke-policy.yaml
  scripts/lke_calico_rules_e2e.sh
Labels: testing

#1476 doc: Add documentation notes for Placement Groups LA
  docs/data-sources/placement_group.md
  docs/data-sources/placement_groups.md
  docs/resources/instance.md
  docs/resources/placement_group.md
  docs/resources/placement_group_assignment.md
Labels: documentation

#1465 add `obj_bucket_force_delete` config option to delete buckets with objects
  docs/index.md
  linode/framework_provider.go
  linode/framework_provider_config.go
  linode/helper/config.go
  linode/helper/framework_provider_model.go
  linode/helper/objects.go
  linode/objbucket/resource.go
  linode/objbucket/resource_test.go
  linode/objbucket/tmpl/force_delete.gotf
  linode/objbucket/tmpl/force_delete_empty.gotf
  linode/objbucket/tmpl/template.go
  linode/provider.go
Labels: improvement

#1487 test: Resolve issue in failing Placement Group tests
  linode/instance/resource_test.go
  linode/placementgroups/datasource_test.go
Labels: testing

#1478 Require replacement when `type` attribute of node pool resource changed
  linode/lkenodepool/framework_resource_schema.go
  linode/lkenodepool/framework_resource_test.go
  linode/lkenodepool/tmpl/nodepool.gotf
  linode/lkenodepool/tmpl/template.go
Labels: bugfix
