Repository linode/terraform-provider-linode, pull requests merged in 2025-10, with the labels that each got.

#2086 VPC Dual Stack: Add support in Legacy (Config) Interfaces
  docs/data-sources/instances.md
  docs/resources/instance.md
  docs/resources/instance_config.md
  linode/helper/customtypes/autoallocrange.go
  linode/helper/diffsuppressfuncs/autoallocrange.go
  linode/helper/instance.go
  linode/helper/networking.go
  linode/instance/datasource_test.go
  linode/instance/resource_test.go
  linode/instance/schema_resource.go
  linode/instance/tmpl/template.go
  linode/instance/tmpl/templates/config_interfaces_vpc_ipv6.gotf
  linode/instance/tmpl/templates/data_interfaces_vpc_ipv6.gotf
  linode/instance/tmpl/templates/interfaces_vpc_ipv6_0.gotf
  linode/instance/tmpl/templates/interfaces_vpc_ipv6_1.gotf
  linode/instanceconfig/resource_test.go
  linode/instanceconfig/tmpl/template.go
  linode/instanceconfig/tmpl/vpc_interface_ipv6_0.gotf
  linode/instanceconfig/tmpl/vpc_interface_ipv6_1.gotf
Labels: new-feature

#2119 Poll for database active after applying `updates` during creation; ignore members on database import test step; fix Instance Config assertions
  linode/databasemysqlv2/framework_resource.go
  linode/databasemysqlv2/resource_test.go
  linode/databasepostgresqlv2/framework_resource.go
  linode/databasepostgresqlv2/resource_test.go
  linode/instanceconfig/resource_test.go
Labels: bugfix

#2092 Add RFC3339 custom type for `created` attribute of OBJ bucket data source
  linode/objbucket/framework_datasource.go
  linode/objbucket/framework_datasource_schema.go
  linode/objbucket/framework_models.go
Labels: improvement

#2088 Multiple miscellaneous updates
  linode/helper/framework_schema.go
  linode/instance/helpers.go
  linode/instance/resource.go
  linode/user/framework_models_unit_test.go
Labels: improvement, bugfix

#2123 Fix instance resource boot status waiting
  linode/instance/resource.go
Labels: ignore-for-release

#2122 NodeBalancer VPC: Temporary workaround for ipv4_range bug
  linode/nb/framework_models.go
  linode/nb/framework_resource_schema.go
Labels: bugfix
