Repository linode/terraform-provider-linode, pull requests merged in 2025-01, with the labels that each got.

#1700 Deduplicate computed obj key regions; defer default value of `cors_enabled` to the API
  linode/objbucket/schema_resource.go
  linode/objkey/framework_model.go
Labels: breaking-change

#1695 Remove unnecessary permissions for codeql scan workflow
  .github/workflows/codeql.yml
Labels: ignore-for-release

#1708 Use filter framework for linode_networking_ips data source
  linode/networkingips/famework_datasource_schema.go
  linode/networkingips/framework_datasource.go
  linode/networkingips/framework_datasource_models.go
  linode/networkingips/tmpl/data_filter.gotf
  linode/networkingips/tmpl/data_list.gotf
Labels: improvement

#1710 Drop linode_reserved_ip resource and data sources in favor of linode_networking_ip
  linode/framework_provider.go
  linode/instance/resource_test.go
  linode/instance/tmpl/template.go
  linode/instance/tmpl/templates/instance_with_reserved_ip.gotf
  linode/instancereservedipassignment/tmpl/AddReservedIPToInstance.gotf
  linode/reservedip/datasource_model.go
  linode/reservedip/datasource_schema.go
  linode/reservedip/datasource_test.go
  linode/reservedip/framework_datasource.go
  linode/reservedip/framework_models.go
  linode/reservedip/framework_resource.go
  linode/reservedip/framework_schema.go
  linode/reservedip/resource_test.go
  linode/reservedip/tmpl/reserved_ip.gotf
  linode/reservedip/tmpl/reserved_ip_basic.gotf
  linode/reservedip/tmpl/template.go
  linode/reservedips/datasource_model.go
  linode/reservedips/datasource_schema.go
  linode/reservedips/datasource_test.go
  linode/reservedips/framework_datasource.go
  linode/reservedips/tmpl/reserved_ip.gotf
  linode/reservedips/tmpl/template.go
Labels: improvement

#1688 Added support for migrations field for Placement Group Datasource
  docs/data-sources/placement_group.md
  docs/data-sources/placement_groups.md
  linode/placementgroup/framework_datasource_schema.go
  linode/placementgroup/framework_models.go
Labels: improvement

#1680 Add linode_database_postgresql_v2 resource
  .github/workflows/integration_tests.yml
  docs/resources/database_postgresql_v2.md
  go.mod
  go.sum
  linode/databaseaccesscontrols/resource.go
  linode/databaseaccesscontrols/resource_test.go
  linode/databaseaccesscontrols/schema_resource.go
  linode/databaseaccesscontrols/tmpl/postgresql.gotf
  linode/databasepostgresqlv2/framework_models.go
  linode/databasepostgresqlv2/framework_models_unit_test.go
  linode/databasepostgresqlv2/framework_resource.go
  linode/databasepostgresqlv2/framework_resource_schema.go
  linode/databasepostgresqlv2/resource_test.go
  linode/databasepostgresqlv2/tmpl/basic.gotf
  linode/databasepostgresqlv2/tmpl/complex.gotf
  linode/databasepostgresqlv2/tmpl/fork.gotf
  linode/databasepostgresqlv2/tmpl/template.go
  linode/framework_provider.go
  linode/helper/database.go
  linode/helper/framework_util.go
  linode/helper/iterator.go
  linode/helper/unit/framework_util.go
  tools/go.mod
Labels: new-feature

#1714 doc: Add doc example to grand explicit access to multiple buckets
  docs/resources/object_storage_key.md
Labels: documentation

#1702 Preserve booted status from state if instance is booted but boot event is unresolvable
  linode/instanceconfig/helper.go
  linode/instanceconfig/resource.go
Labels: bugfix

#1707 Deprecate legacy DBaaS resources
  docs/data-sources/database_backups.md
  docs/data-sources/database_mysql.md
  docs/data-sources/database_mysql_backups.md
  docs/data-sources/database_postgresql.md
  docs/resources/database_mysql.md
  docs/resources/database_postgresql.md
  linode/databasebackups/framework_datasource_schema.go
  linode/databasemysql/framework_datasource_schema.go
  linode/databasemysql/resource.go
  linode/databasemysqlbackups/datasource.go
  linode/databasepostgresql/framework_datasource_schema.go
  linode/databasepostgresql/resource.go
Labels: documentation, improvement

#1701 Add linode_database_mysql_v2 resource
  .github/workflows/integration_tests.yml
  docs/resources/database_mysql_v2.md
  linode/databaseaccesscontrols/resource_test.go
  linode/databaseaccesscontrols/tmpl/mysql.gotf
  linode/databasemysqlv2/framework_models.go
  linode/databasemysqlv2/framework_models_unit_test.go
  linode/databasemysqlv2/framework_resource.go
  linode/databasemysqlv2/framework_resource_schema.go
  linode/databasemysqlv2/resource_test.go
  linode/databasemysqlv2/tmpl/basic.gotf
  linode/databasemysqlv2/tmpl/complex.gotf
  linode/databasemysqlv2/tmpl/fork.gotf
  linode/databasemysqlv2/tmpl/template.go
  linode/framework_provider.go
Labels: new-feature

#1716 Implement `linode_database_postgresql_v2` data source
  docs/data-sources/database_postgresql_v2.md
  docs/resources/database_postgresql_v2.md
  linode/databasepostgresqlv2/datasource_test.go
  linode/databasepostgresqlv2/framework_datasource.go
  linode/databasepostgresqlv2/framework_models.go
  linode/databasepostgresqlv2/framework_resource.go
  linode/databasepostgresqlv2/framework_schema_datasource.go
  linode/databasepostgresqlv2/tmpl/data.gotf
  linode/databasepostgresqlv2/tmpl/template.go
  linode/framework_provider.go
Labels: new-feature

#1727 Poll for database readiness in `linode_database_postgresql_v2` before applying `updates` field
  linode/databasepostgresqlv2/framework_resource.go
Labels: bugfix

#1729 Add documentation for new networking-related resources & data sources
  docs/data-sources/networking_ip.md
  docs/data-sources/networking_ips.md
  docs/resources/instance.md
  docs/resources/networking_ip.md
  docs/resources/networking_ip_assignment.md
Labels: documentation

#1738 Manually compute CRC32 sum in PutObject helper
  linode/helper/objects.go
  linode/obj/helpers.go
Labels: bugfix

#1733 test/workflow: Update test commands and related workflows
  .github/workflows/integration_tests.yml
  .github/workflows/integration_tests_pr.yml
  .github/workflows/nightly_smoke_tests.yml
  .github/workflows/pull_request.yml
  .github/workflows/unit-tests.yml
  Makefile
  README.md
  linode/firewalls/datasource_test.go
  linode/instance/resource_test.go
Labels: repo-ci-improvement, testing

#1726 Added support for NodeBalancers UDP
  docs/data-sources/nodebalancer.md
  docs/data-sources/nodebalancer_config.md
  docs/data-sources/nodebalancer_configs.md
  docs/resources/nodebalancer.md
  docs/resources/nodebalancer_config.md
  go.mod
  go.sum
  linode/nb/datasource_test.go
  linode/nb/framework_datasource_schema.go
  linode/nb/framework_models.go
  linode/nb/framework_models_unit_test.go
  linode/nb/framework_resource.go
  linode/nb/framework_resource_schema.go
  linode/nb/resource_test.go
  linode/nb/tmpl/basic.gotf
  linode/nb/tmpl/updates.gotf
  linode/nbconfig/datasource_test.go
  linode/nbconfig/framework_models.go
  linode/nbconfig/framework_schema_datasource.go
  linode/nbconfig/framework_schema_resource.go
  linode/nbconfig/resource_test.go
  linode/nbconfig/tmpl/updates.gotf
  linode/nbconfigs/datasource_test.go
Labels: new-feature

#1718 new: Support `tier` in LKE resource and data source
  docs/data-sources/lke_cluster.md
  docs/data-sources/lke_clusters.md
  docs/resources/lke_cluster.md
  go.mod
  linode/lke/framework_datasource_schema.go
  linode/lke/framework_datasource_test.go
  linode/lke/framework_models.go
  linode/lke/framework_resource_test.go
  linode/lke/resource.go
  linode/lke/schema_resource.go
  linode/lke/tmpl/autoscaler.gotf
  linode/lke/tmpl/autoscaler_many_pools.gotf
  linode/lke/tmpl/autoscaler_no_count.gotf
  linode/lke/tmpl/autoscaler_updates.gotf
  linode/lke/tmpl/basic.gotf
  linode/lke/tmpl/complex_pools.gotf
  linode/lke/tmpl/control_plane.gotf
  linode/lke/tmpl/many_pools.gotf
  linode/lke/tmpl/taints_labels.gotf
  linode/lke/tmpl/updates.gotf
  linode/lkeclusters/datasource_test.go
  linode/lkeclusters/framework_datasource_schema.go
  linode/lkeclusters/framework_models.go
  linode/lkeclusters/tmpl/data_base.gotf
  linode/lkeclusters/tmpl/data_filter.gotf
Labels: new-feature
