Repository linode/terraform-provider-linode, pull requests merged in 2025-04, with the labels that each got.

#1825 Migrate account login data source to be based on the base data source
  linode/accountlogin/framework_datasource.go
Labels: improvement

#1832 Support enterprise feature in node pool resource and improve its update logic
  docs/resources/lke_node_pool.md
  go.mod
  go.sum
  linode/lkenodepool/framework_models.go
  linode/lkenodepool/framework_models_unit_test.go
  linode/lkenodepool/framework_resource.go
  linode/lkenodepool/framework_resource_schema.go
  linode/lkenodepool/framework_resource_test.go
  linode/lkenodepool/tmpl/lke_e_nodepool.gotf
  linode/lkenodepool/tmpl/template.go
Labels: new-feature, improvement

#1833 Restore update polling and add resize polling for DBaaS V2 Resources
  linode/databasemysqlv2/framework_resource.go
  linode/databasepostgresqlv2/framework_resource.go
Labels: improvement

#1842 Fix control plane acl test
  linode/lke/framework_resource_test.go
Labels: testing

#1811 LKE Cluster APL Support
  .gitignore
  docs/data-sources/lke_cluster.md
  docs/resources/lke_cluster.md
  linode/lke/framework_datasource_schema.go
  linode/lke/framework_models.go
  linode/lke/framework_resource_test.go
  linode/lke/resource.go
  linode/lke/schema_resource.go
  linode/lke/tmpl/apl.gotf
  linode/lke/tmpl/template.go
  linode/lkeclusters/framework_datasource_schema.go
Labels: improvement

#1848 Avoid sending invalid nodepool create options
  linode/lkenodepool/framework_models.go
Labels: bugfix

#1851 Add alp_enabled variable to LKEClusterModel struct
  linode/lkeclusters/framework_models.go
Labels: improvement

#1849 Deprecate `ip_address` attribute of `linode_instance` resource
  docs/data-sources/instances.md
  linode/instance/schema_resource.go
Labels: improvement

#1855 Fix typo
  linode/obj/framework_models.go
Labels: ignore-for-release
