Repository linode/terraform-provider-linode, pull requests merged in 2025-06, with the labels that each got.

#1896 Support `config_id` in the linode interfaces in subnet resources and data sources
  linode/helper/conversion.go
  linode/vpcsubnet/framework_models.go
  linode/vpcsubnet/framework_schema_resource.go
  linode/vpcsubnets/datasource_test.go
  linode/vpcsubnets/framework_datasource_test.go
Labels: new-feature

#1925 extended-support/v2: Set EOL date in documentation
  README.md
  docs/index.md
Labels: ignore-for-release

#1890 Linode Interfaces: Implement changes under linode_instance resource and data source
  docs/data-sources/instance_networking.md
  docs/data-sources/instances.md
  docs/resources/instance.md
  go.mod
  go.sum
  linode/instance/datasource.go
  linode/instance/datasource_test.go
  linode/instance/flatten.go
  linode/instance/resource.go
  linode/instance/resource_test.go
  linode/instance/schema_datasource.go
  linode/instance/schema_resource.go
  linode/instance/tmpl/template.go
  linode/instance/tmpl/templates/data_explicit_interface_generation.gotf
  linode/instance/tmpl/templates/explicit_interface_generation.gotf
  linode/instancenetworking/datasource_test.go
  linode/instancenetworking/framework_datasource_schema.go
  linode/instancenetworking/framework_models.go
Labels: new-feature, do-not-merge
