Repository linode/terraform-provider-linode, pull requests merged in 2025-02, with the labels that each got.

#1744 Add object storage endpoints data source
  docs/data-sources/object_storage_endpoints.md
  linode/framework_provider.go
  linode/objendpoints/framework_datasource.go
  linode/objendpoints/framework_datasource_schema.go
  linode/objendpoints/framework_datasource_test.go
  linode/objendpoints/framework_models.go
  linode/objendpoints/tmpl/basic.gotf
  linode/objendpoints/tmpl/filter.gotf
  linode/objendpoints/tmpl/template.go
Labels: new-feature

#1755 Update DB forked test cases
  linode/databasemysqlv2/resource_test.go
  linode/databasepostgresqlv2/resource_test.go
Labels: testing

#1748 Fix `port` in mysqlv2 resource
  linode/databasemysqlv2/framework_models.go
Labels: bugfix

#1754 Fix issue causing DBs to get recreated with every update
  linode/databasemysqlv2/framework_resource.go
  linode/databasemysqlv2/framework_resource_schema.go
  linode/databasepostgresqlv2/framework_resource.go
  linode/databasepostgresqlv2/framework_resource_schema.go
  linode/helper/compare.go
Labels: bugfix

#1746 Fix multiple miscellaneous issues
  linode/firewall/framework_models.go
  linode/image/framework_resource.go
  linode/objkey/framework_model.go
  linode/rdns/framework_resource.go
Labels: bugfix

#1728 Update Linode resize to differentiate between warm and cold migrations
  linode/instance/helpers.go
Labels: bugfix

#1767 Bump golangci-lint -> v1.64.4
  tools/go.mod
  tools/go.sum
Labels: dependencies

#1773 fix: Replace update polling with status polling for DBaaS v2 updates
  linode/databasemysqlv2/framework_resource.go
  linode/databasepostgresqlv2/framework_resource.go
Labels: bugfix

#1774 Separate legacy and Aiven-backed database engine slug helpers
  linode/databasemysql/framework_models.go
  linode/databasemysql/framework_models_unit_test.go
  linode/databasemysql/resource.go
  linode/databasepostgresql/framework_models.go
  linode/databasepostgresql/framework_models_unit_test.go
  linode/databasepostgresql/resource.go
  linode/helper/database.go
Labels: bugfix

#1775 Remove LKE ACL LA notices
  docs/data-sources/lke_cluster.md
  docs/resources/lke_cluster.md
Labels: documentation

#1788 Fix multiple issues with LKE Enterprise
  docs/data-sources/lke_cluster.md
  docs/resources/lke_cluster.md
  linode/lke/cluster.go
  linode/lke/framework_datasource.go
  linode/lke/framework_models.go
  linode/lke/framework_resource_test.go
  linode/lke/resource.go
  linode/lke/tmpl/enterprise.gotf
  linode/lke/tmpl/template.go
Labels: bugfix

#1789 Fixed issues in DBaaS V2 documentation
  docs/data-sources/database_mysql_v2.md
  docs/data-sources/database_postgresql_v2.md
  docs/resources/database_mysql_v2.md
  docs/resources/database_postgresql_v2.md
Labels: documentation

#1787 Correct the key for bucket label
  linode/helper/objects.go
Labels: bugfix

#1791 Ignored updated field DBaaS v2 tests
  linode/databasemysqlv2/resource_test.go
  linode/databasepostgresqlv2/resource_test.go
Labels: testing

#1792 Separated resize from update in DBaaS V2 tests
  linode/databasemysqlv2/resource_test.go
  linode/databasepostgresqlv2/resource_test.go
Labels: testing

#1794 Fix LKE control plane ACL test to match the updated API behavior
  linode/lke/framework_resource_test.go
Labels: testing

#1790 Release v2.34.2
  docs/data-sources/database_mysql_v2.md
  docs/data-sources/database_postgresql_v2.md
  docs/data-sources/lke_cluster.md
  docs/resources/database_mysql_v2.md
  docs/resources/database_postgresql_v2.md
  docs/resources/lke_cluster.md
  docs/resources/object_storage_bucket.md
  docs/resources/object_storage_key.md
  go.mod
  go.sum
  linode/databasemysql/framework_models.go
  linode/databasemysql/framework_models_unit_test.go
  linode/databasemysql/resource.go
  linode/databasemysqlv2/framework_resource.go
  linode/databasemysqlv2/resource_test.go
  linode/databasepostgresql/framework_models.go
  linode/databasepostgresql/framework_models_unit_test.go
  linode/databasepostgresql/resource.go
  linode/databasepostgresqlv2/framework_resource.go
  linode/databasepostgresqlv2/resource_test.go
  linode/helper/database.go
  linode/helper/objects.go
  linode/instance/schema_resource.go
  linode/lke/cluster.go
  linode/lke/framework_datasource.go
  linode/lke/framework_models.go
  linode/lke/framework_resource_test.go
  linode/lke/resource.go
  linode/lke/tmpl/enterprise.gotf
  linode/lke/tmpl/template.go
  tools/go.mod
  tools/go.sum
Labels: ignore-for-release
