Repository linode/terraform-provider-linode, pull requests merged in 2025-09, with the labels that each got.

#2077 Only use regions compatible with custom images for image tests
  linode/helper/iterator.go
  linode/image/resource_test.go
Labels: testing

#2076 Updated documentation link in maintenance policies datasource docs
  docs/data-sources/maintenance_policies.md
Labels: documentation

#2078 UseStateForUnknown on database sensitive values only if not null
  linode/databasemysqlv2/framework_resource_schema.go
  linode/databasepostgresqlv2/framework_resource_schema.go
  linode/firewall/framework_schema_resource.go
  linode/helper/setplanmodifiers/caseinsensitiveset.go
  linode/helper/setplanmodifiers/caseinsensitiveset_test.go
  linode/helper/stringplanmodifiers/usestateforunknownif.go
  linode/lkenodepool/framework_resource_schema.go
  linode/nb/framework_resource_schema.go
  linode/volume/framework_schema_resource.go
Labels: bugfix

#2079 Support LKE-E phase 2: Bring Your Own VPC, Dual Stack Cluster, Audit Log Enabling
  docs/data-sources/lke_cluster.md
  docs/data-sources/lke_clusters.md
  docs/resources/lke_cluster.md
  go.mod
  go.sum
  linode/lke/cluster.go
  linode/lke/framework_datasource_schema.go
  linode/lke/framework_datasource_test.go
  linode/lke/framework_models.go
  linode/lke/framework_resource_test.go
  linode/lke/resource.go
  linode/lke/schema_resource.go
  linode/lke/tmpl/enterprise.gotf
  linode/lke/tmpl/template.go
  linode/lkeclusters/framework_datasource_schema.go
  linode/lkeclusters/framework_models.go
Labels: new-feature

#2084 Stabilize image uploading integrate test by restricting the regions
  linode/image/resource_test.go
Labels: testing
