Repository linode/terraform-provider-linode, pull requests merged in 2025-05, with the labels that each got.

#1863 Update prefix in instance.md ipv6 example
  docs/data-sources/instances.md
  docs/resources/instance.md
  linode/instance/resource_test.go
Labels: documentation

#1861 Fix label update and minor bug in LKE node pool resource
  linode/lkenodepool/framework_models.go
Labels: bugfix

#1854 linode_lke_node_pool: Resolve LKE node pool autoscaler disable error when using explicit node_count
  linode/lkenodepool/framework_models.go
  linode/lkenodepool/framework_resource_test.go
  linode/lkenodepool/tmpl/nodepool.gotf
Labels: bugfix

#1859 Added support for Configurable DB Params
  docs/data-sources/database_mysql_config.md
  docs/data-sources/database_mysql_v2.md
  docs/data-sources/database_postgresql_config.md
  docs/data-sources/database_postgresql_v2.md
  docs/resources/database_mysql_v2.md
  docs/resources/database_postgresql_v2.md
  go.mod
  go.sum
  linode/databasemysqlconfig/datasource_test.go
  linode/databasemysqlconfig/framework_datasource.go
  linode/databasemysqlconfig/framework_datasource_schema.go
  linode/databasemysqlconfig/framework_models.go
  linode/databasemysqlconfig/tmpl/data_basic.gotf
  linode/databasemysqlconfig/tmpl/template.go
  linode/databasemysqlv2/datasource_test.go
  linode/databasemysqlv2/framework_datasource_schema.go
  linode/databasemysqlv2/framework_models.go
  linode/databasemysqlv2/framework_models_unit_test.go
  linode/databasemysqlv2/framework_resource.go
  linode/databasemysqlv2/framework_resource_schema.go
  linode/databasemysqlv2/resource_test.go
  linode/databasemysqlv2/tmpl/data_engine_config.gotf
  linode/databasemysqlv2/tmpl/engine_config.gotf
  linode/databasemysqlv2/tmpl/engine_config_nullable_field.gotf
  linode/databasemysqlv2/tmpl/template.go
  linode/databasepostgresqlconfig/datasource_test.go
  linode/databasepostgresqlconfig/framework_datasource.go
  linode/databasepostgresqlconfig/framework_datasource_schema.go
  linode/databasepostgresqlconfig/framework_models.go
  linode/databasepostgresqlconfig/tmpl/data_basic.gotf
  linode/databasepostgresqlconfig/tmpl/template.go
  linode/databasepostgresqlv2/datasource_test.go
  linode/databasepostgresqlv2/framework_models.go
  linode/databasepostgresqlv2/framework_models_unit_test.go
  linode/databasepostgresqlv2/framework_resource.go
  linode/databasepostgresqlv2/framework_resource_schema.go
  linode/databasepostgresqlv2/framework_schema_datasource.go
  linode/databasepostgresqlv2/resource_test.go
  linode/databasepostgresqlv2/tmpl/data_engine_config.gotf
  linode/databasepostgresqlv2/tmpl/engine_config.gotf
  linode/databasepostgresqlv2/tmpl/engine_config_update.gotf
  linode/databasepostgresqlv2/tmpl/template.go
  linode/framework_provider.go
  linode/helper/compare.go
  linode/helper/conversion.go
  linode/helper/framework_data.go
Labels: new-feature, do-not-merge

#1868 Update Object Storage quota API doc links
  docs/data-sources/object_storage_quota.md
  docs/data-sources/object_storage_quotas.md
Labels: documentation

#1864 Add `interfaces_for_new_linodes` attribute in the account settings resource and data source
  linode/accountsettings/datasource_test.go
  linode/accountsettings/framework_datasource_schema.go
  linode/accountsettings/framework_model.go
  linode/accountsettings/framework_model_unit_test.go
  linode/accountsettings/framework_resource.go
  linode/accountsettings/framework_resource_schema.go
  linode/accountsettings/resource_test.go
  linode/accountsettings/tmpl/template.go
  linode/accountsettings/tmpl/updates.gotf
Labels: new-feature

#1876 Updated type for modified fields
  go.mod
  go.sum
  linode/databasepostgresqlconfig/datasource_test.go
  linode/databasepostgresqlconfig/framework_datasource_schema.go
  linode/databasepostgresqlconfig/framework_models.go
Labels: bugfix
